### ISSUE TITLE
font not displaying gifs under linux

### ISSUE THREAD

**Issue by linuxclowns** [jackhumbert/sitelen-pona-pona#1]
The font is only displaying latin characters in inkscape and abiword.

**Comment by jackhumbert** [comment]
You need to be able to turn on the Stylistic Alternatives - in Inkscape I think that's done with this: http://vid.bina.me/typography/stylistic-variants-in-inkscape/ - `salt` is the table you want to enable. I'm not sure AbiWord supports OpenTypr features like that.

**Comment by linuxclowns** [comment]
I gave this a try in inkscape, and it did not enable the glyphs.

Curious why other fonts like linja pona work in both abiword and inkscape out of the box.

**Comment by jackhumbert** [comment]
![image](https://user-images.githubusercontent.com/141431/76689957-becffb80-6611-11ea-9e04-292111a1ce52.png)

Typing in `salt` in the feature settings and clicking apply works for me on Windows. I think linja pona uses the `liga` table, which may be enabled by default - I didn't put it in this table because I wanted Latin and sitelen pona text to be able to mixed together easily. I was debating assembling a version that only renders SP though.

**Comment by jackhumbert** [comment]
I moved things over to the liga table - would you be able to try out the new version to see if it works more easily for you? https://github.com/jackhumbert/sitelen-pona-pona/releases/tag/v0.2

**Comment by jackhumbert** [comment]
Awesome, thanks for confirming :)
